### ISSUE TITLE
PlayAlbum Example not working

### ISSUE THREAD

**Issue by Alwiz79** [Jaffa/amazon-music#22]
```
play-album.py B0170UQ0OC
Email: my-email-here
Amazon password:
Traceback (most recent call last):
  File "/home/pi/amazon-music-master/play-album.py", line 32, in <module>
    album = am.get_album(asin)
  File "/home/pi/amazon-music-master/amazonmusic.py", line 265, in get_album
    )['albumList'][0]
IndexError: list index out of range
```

Any idea what is happening here?

**Comment by mkanet** [comment]
I was going to open an issue like you did, but it looks like this amazon-music solution has been abandoned for some time.
