### ISSUE TITLE
    raise Exception("Unable to find appConfig in {}".format(r.content))

### ISSUE THREAD

**Issue by StefanoGiu** [Jaffa/amazon-music#34]
Traceback (most recent call last):
  File "play-playlist.py", line 27, in <module>
    am = AmazonMusic(credentials = lambda: [input('Email: '), getpass('Amazon password: ')])
  File "C:\Users\estgiug\Desktop\amazon-music-master\amazonmusic.py", line 111, in __init__
    raise Exception("Unable to find appConfig in {}".format(r.content))
Exception: Unable to find appConfig in b'\n<!doctype html>\n<html>\n<head>\n    <title>Libreria musicale di Amazon</title>\n    <style type="text/css">\n        body {\n            background-color: white;\n            background-image: none;\n            filter: none;\n            overflow: scroll;\n            font: 16px/1.5 "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;\n            -webkit-font-smoothing: antialiased;\n            text-rendering: optimizeLegibility;\n            color: #7c8289;\n            letter-spacing: .5px;\n        }\n\n        #contentContainer {\n            padding:10px;\n            margin-top:80px;\n            text-align: center;\n        }\n\n        .playerIconHeadphonesError {\n            margin-top: 2rem;\n            font-size: 14rem;\n        }\n\n        .mainErrorText {\n            font-size: 1.5rem;\n            margin-top: 3rem;\n        }\n\n        .secondaryText {\n            font-size: 1.5rem;\n            margin-top: 1rem;\n        }\n\n        .secondaryText {\n            font-size: 1rem;\n        }\n\n        .mainErrorText, .secondaryText {\n            color: #000;\n            margin-bottom: 0.5rem;\n            display: block;\n        }\n\n        .amazonMusicLogo {\n            background-image: url("https://m.media-amazon.com/images/G/01/digital/music/player/web/AmazonMusicLogoPurple.svg");\n            background-repeat: no-repeat;\n            height: 100px;\n            width: 325px;\n            margin: 0px auto;\n        }\n\n        a {\n            color: rgba(253,124,2,1);\n        }\n    </style>\n</head>\n<body>\n<section id="contentContainer">\n    <span class="mainErrorText">Stiamo riscontrando un errore.</span>\n    <span class="secondaryText">\n        Ci scusiamo. Il servizio sar\xc3\xa0 disponibile presto.\n    </span>\n    <a href="">Indietro</a>\n    <div class="imageContainer">\n        <div class="playerIconHeadphonesError">\n            <img src="https://images-na.ssl-images-amazon.com/images/G/01/digital/music/player/recs-error-headphones._CB290417569_.png" />\n        </div>\n        <br />\n        <div class="amazonMusicLogo"></div>\n    </div>\n    \n</section>\n</body>\n'

**Comment by SpEcHiDe** [comment]
>>> am = AmazonMusic()

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/amazonmusic.py", line 111, in __init__
    raise Exception("Unable to find appConfig in {}".format(r.content))
Exception: Unable to find appConfig in b'<!DOCTYPE html>\n<html>\n<head>\n    <style type="text/css">\n\n    html, body {\n            background-color: rgba(0, 0, 0, 0);\n            background-image: linear-gradient(black, rgb(31, 34, 34));\n            color: white;\n            font-family: Amazon Ember;\n            font-size: 15px;\n            line-height: 20px;\n            height: 100%;\n        }\n\n        #container {\n            width: 448px;\n            height: 100%;\n            margin: 0 auto !important;\n            text-align: center;\n            position: relative;\n        }\n\n        #content {\n            position: absolute;\n            top: 50%;\n            transform: translateY(-50%);\n        }\n\n        .amazonMusicLogo {\n            height: 48px;\n            margin: 0 auto;\n        }\n\n        .heading {\n            font-weight: bold;\n            font-size: 20px;\n            font-family: Amazon Ember Medium;\n        }\n\n        .title {\n            margin-top: 32px;\n            margin-bottom: 16px;\n        }\n\n        .message a {\n            color: #1AD2FB;\n        }\n\n        .button {\n            display:inline-block;\n            background-color: rgba(26, 210, 251, 0.75);\n            color: black;\n            border: 2px solid transparent;\n            box-shadow: none;\n            padding: 6px 16px;\n            text-decoration: none;\n            font-size: 14px;\n            line-height: 20px;\n            border-collapse: separate;\n            border-spacing: 2px;\n            pointer-events: auto;\n            cursor: pointer;\n            outline: none;\n            border-radius: 300px;\n        }\n</style>\n<title></title>\n\n</head>\n<body>\n    <div id="container">\n    <div id="content">\n        <!-- We cannot have EJS escape our urls -->\n        <img class="amazonMusicLogo" src="https://m.media-amazon.com/images/G/01/music-tv/music_logo.png">\n        <h2 class="heading title">Your browser is not supported </h2>\n        <p class="message">For the best experience accessing Amazon Music we recommend using the latest version of <a href="https://www.mozilla.org/firefox" rel="noreferrer">Firefox</a>, <a href="https://www.google.com/chrome/" rel="noreferrer">Chrome</a>, <a href="https://support.apple.com/downloads/#safari" rel="noreferrer">Safari</a> or <a href="https://www.microsoft.com/en-us/windows/microsoft-edge" rel="noreferrer">Edge</a>.</p>\n        \n    </div>\n</div>\n</body>\n</html>\n'
```


## I get the same error

**Comment by J0hnnyF1v3** [comment]
Similar issue for me;
`>>> am = AmazonMusic(credentials = lambda: [input('Email: '), getpass('Amazon pw: ')])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/xxx/amznMusic/amazon-music/amazonmusic.py", line 111, in __init__
    raise Exception("Unable to find appConfig in {}".format(r.content))
Exception: Unable to find appConfig in b'<!DOCTYPE html>\n<html>\n<head>\n    <style type="text/css">\n\n    html, body {\n            background-color: rgba(0, 0, 0, 0);\n            background-image: linear-gradient(black, rgb(31, 34, 34));\n            color: white;\n            font-family: Amazon Ember;\n            font-size: 15px;\n            line-height: 20px;\n            height: 100%;\n        }\n\n        #container {\n            width: 448px;\n            height: 100%;\n            margin: 0 auto !important;\n            text-align: center;\n            position: relative;\n        }\n\n        #content {\n            position: absolute;\n            top: 50%;\n            transform: translateY(-50%);\n        }\n\n        .amazonMusicLogo {\n            height: 48px;\n            margin: 0 auto;\n        }\n\n        .heading {\n            font-weight: bold;\n            font-size: 20px;\n            font-family: Amazon Ember Medium;\n        }\n\n        .title {\n            margin-top: 32px;\n            margin-bottom: 16px;\n        }\n\n        .message a {\n            color: #1AD2FB;\n        }\n\n        .button {\n            display:inline-block;\n            background-color: rgba(26, 210, 251, 0.75);\n            color: black;\n            border: 2px solid transparent;\n            box-shadow: none;\n            padding: 6px 16px;\n            text-decoration: none;\n            font-size: 14px;\n            line-height: 20px;\n            border-collapse: separate;\n            border-spacing: 2px;\n            pointer-events: auto;\n            cursor: pointer;\n            outline: none;\n            border-radius: 300px;\n        }\n</style>\n<title></title>\n\n</head>\n<body>\n    <div id="container">\n    <div id="content">\n        \n        <img class="amazonMusicLogo" src="https://m.media-amazon.com/images/G/01/music-tv/music_logo.png">\n        <h2 class="heading title">Your browser is not supported </h2>\n        <p class="message">For the best experience accessing Amazon Music we recommend using the latest version of <a href="https://www.mozilla.org/firefox" rel="noreferrer">Firefox</a>, <a href="https://www.google.com/chrome/" rel="noreferrer">Chrome</a>, <a href="https://support.apple.com/downloads/#safari" rel="noreferrer">Safari</a> or <a href="https://www.microsoft.com/en-us/windows/microsoft-edge" rel="noreferrer">Edge</a>.</p>\n        \n    </div>\n</div>\n</body>\n</html>\n'`

From the above it looks like Amazon does not like the "browser" I'm using, "Your browser is not supported". Bummer. Any chance this can be remedied? Maybe updated python libraries?
