### ISSUE TITLE
CONTENT_NOT_VALID

### ISSUE THREAD

**Issue by StefanoGiu** [Jaffa/amazon-music#36]
Art: https://images-na.ssl-images-amazon.com/images/I/71Uwz5YJlWL._CLa%7C1000,1000%7C61blNmsIFwL.png,719v1WesHcL.png,71J8+2zMNjL.png%7C0,0,500,500+500,0,500,500+0,500,500,500+500,500,500,500_BG34,34,34L.png
Playing station Classic Soul...
Playing Feeling Good by Nina Simone from Feeling Good [Nina Simone]...
Traceback (most recent call last):
  File "play-station.py", line 37, in <module>
    os.system("cvlc --play-and-exit '%s'" % t.stream_url)
  File "C:\Users\estgiug\Desktop\amazon-music-master\amazonmusic.py", line 690, in stream_url
    self._url = stream_json['contentResponse']['urlList'][0]
KeyError: 'contentResponse not found in {"__type": "com.amazon.digitalmusiclocator#BadRequestException", "errorCode": "CONTENT_NOT_VALID", "message": "InvalidContentId"}'

**Comment by PhilippRott** [comment]
same here...

Art: https://images-na.ssl-images-amazon.com/images/I/71Uwz5YJlWL._CLa%7C1000,1000%7C61blNmsIFwL.png,719v1WesHcL.png,71J8+2zMNjL.png%7C0,0,500,500+500,0,500,500+0,500,500,500+500,500,500,500_BG34,34,34L.png
Playing station Classic Soul...
Playing Ain't No Mountain High Enough by Marvin Gaye & Tammi Terrell from Greatest Hits [Marvin Gaye & Tammi Terrell]...
Traceback (most recent call last):
  File "play-station.py", line 37, in <module>
    os.system("cvlc --play-and-exit '%s'" % t.stream_url)
  File "/home/philipp/python/amazon-music/examples/amazonmusic.py", line 690, in stream_url
    self._url = stream_json['contentResponse']['urlList'][0]
KeyError: 'contentResponse not found in {"__type": "com.amazon.digitalmusiclocator#BadRequestException", "errorCode": "CONTENT_NOT_VALID", "message": "InvalidContentId"}'
